### ISSUE TITLE
Mac builds from v90 onwards fail to launch

### ISSUE THREAD

**Issue by alex-ketch** [stencila/stencila#1038]
Somewhere between [these commits](https://github.com/stencila/stencila/compare/v0.90.0...v0.91.0) the distributed Mac apps fail to launch with the following error:

```log
Uncaught Exception:
Error: dlopen(/Applications/Stencila.app/Contents/Resources/app/.webpack/main/native_modules/index.node, 1): Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
Referenced from: /Applications/Stencila.app/Contents/Resources/app/.webpack/main/native_modules/index.node
Reason: no suitable image found.  Did find:
/usr/local/opt/xz/lib/liblzma.5.dylib: code signature in (/usr/local/opt/xz/lib/liblzma.5.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
at Module.load (internal/modules/cjs/loader.js:935:32)
at Module._load (internal/modules/cjs/loader.js:776:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
at Module.require (internal/modules/cjs/loader.js:959:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.6332 (/Applications/Stencila.app/Contents/Resources/app/.webpack/main/index.js:2:226242)
at r (/Applications/Stencila.app/Contents/Resources/app/.webpack/main/index.js:2:255286)
```

**Comment by nokome** [comment]
Thanks for this @alex-ketch. Could you please see if https://github.com/stencila/stencila/releases/tag/v0.97.2 fixes this issue.

**Comment by alex-ketch** [comment]
Thanks @nokome! I can confirm that the issue is now fixed :)
