### ISSUE TITLE
Typescript/ts-node compile error using @stencila/node - Could not find a declaration file for module '@stencila/node'

### ISSUE THREAD

**Issue by scottaubrey** [stencila/stencila#1705]
# Description

Using yarn, ts-node and typescript, I don't seem to be able to import the library.

## Steps to reproduce

```
> mkdir test
> cd test/
> yarn add typescript ts-node @stencila/node
> echo "import { convert } from '@stencila/node';" >> test.ts
> yarn ts-node ./test.ts
```

Output:
```
yarn add v1.22.17
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 20 new dependencies.
info Direct dependencies
├─ @stencila/node@2.0.0-alpha.16
├─ ts-node@10.9.1
└─ typescript@5.2.2
info All dependencies
├─ @cspotcode/source-map-support@0.8.1
├─ @jridgewell/resolve-uri@3.1.1
├─ @jridgewell/sourcemap-codec@1.4.15
├─ @jridgewell/trace-mapping@0.3.9
├─ @stencila/node@2.0.0-alpha.16
├─ @stencila/types@2.0.0-alpha.16
├─ @tsconfig/node10@1.0.9
├─ @tsconfig/node12@1.0.11
├─ @tsconfig/node14@1.0.3
├─ @tsconfig/node16@1.0.4
├─ acorn-walk@8.2.0
├─ acorn@8.10.0
├─ arg@4.1.3
├─ create-require@1.1.1
├─ diff@4.0.2
├─ make-error@1.3.6
├─ ts-node@10.9.1
├─ typescript@5.2.2
├─ v8-compile-cache-lib@3.0.1
└─ yn@3.1.1
✨  Done in 2.43s.
yarn run v1.22.17
warning package.json: No license field
$ /Users/scottaubrey/test/node_modules/.bin/ts-node ./test.ts
/Users/scottaubrey/test/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
test.ts:1:21 - error TS7016: Could not find a declaration file for module '@stencila/node'. '/Users/scottaubrey/test/node_modules/@stencila/node/dist/lib.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/stencila__node` if it exists or add a new declaration (.d.ts) file containing `declare module '@stencila/node';`

1 import convert from '@stencila/node';
                      ~~~~~~~~~~~~~~~~

    at createTSError (/Users/scottaubrey/test/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/scottaubrey/test/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/scottaubrey/test/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/scottaubrey/test/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/Users/scottaubrey/test/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/scottaubrey/test/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  diagnosticCodes: [ 7016 ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by nokome** [comment]
Thanks for the report @scottaubrey.

I can confirm the issue, which seems to be that the package JSON has `"types": "./dist/lib.d.ts"` when it should be `"types": "./dist/lib.d.mts"`.

In addition to making that fix, I'm going to try some more wrangling of the CJS/ESM bundling so that you can use ESM style `import`s.
